spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      schema: ${SPRING_DATASOURCE_HIKARI_SCHEMA}

bu-credit:
  interest-rate: ${BU_CREDIT_INTEREST_RATE}
